### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by arunvc** [TR-API-Samples/Article.WebSocketAPI.Javascript.QuoteWidget#1]
To run the package, simply load up the quoteObject.html within your browser and follow the instructions. 

![image](https://user-images.githubusercontent.com/9069988/43884332-77f0ed8c-9bd3-11e8-8b9d-5efd0dc71250.png)

**Comment by topacehk** [comment]
In quoteObject.html rename the QuoteObject.js to lowercase q i.e. quoteObject.js

**Comment by arunvc** [comment]
It Works

**Comment by zinc1oxide** [comment]
I've corrected the 'QuoteObject.js' to 'quoteObject.js' issue and committed the changes.  Note: a new version of the widget has been released.
