### ISSUE TITLE
wsService not working

### ISSUE THREAD

**Issue by hoenie-ams** [TR-API-Samples/Article.WebSocketAPI.Javascript.QuoteWidget#2]
Uncommenting the following line breaks the app:
// wsService: 'ELEKTRON_EDGE',   // Optional. Elektron WebSocket service hosting realtime market data
Changing it to any other source (including the default) does not seem to work. Any suggestions? Thanks!

**Comment by zinc1oxide** [comment]
Thanks for pointing this out.  There was a small syntax error in the adsSession structure - missing a comma.  Fix has been uploaded.  You can simply modify your example to include a comma, i.e.:

```adsSession: {
                ...
                position: '127.0.0.1',     // Position.  Optional. Default: '127.0.0.1'
            },  <== Add comma  
            //wsService: 'ELEKTRON_EDGE',   // Optional. Elektron WebSocket service hosting realtime market data              
        },```
